INSERT INTO stox.earnings_growth values ("ACFN","Acorn Energy Inc","--","--","--","--","-14.479");
INSERT INTO stox.earnings_growth values ("ACIA","Acacia Communications","3.18","3.12","3.6","--","--");
INSERT INTO stox.earnings_growth values ("ACTA","Actua Corp","-0.26","--","--","-29.844","-4.9017");
INSERT INTO stox.earnings_growth values ("AEHR","AEHR Test Systems","--","--","--","65.082","1.0884");
INSERT INTO stox.earnings_growth values ("AGYS","Agilysys Inc","-0.18","--","--","9.021","-29.1761");
INSERT INTO stox.earnings_growth values ("AIXNY","Aixtron SE","--","--","--","--","-23.9759");
INSERT INTO stox.earnings_growth values ("AMBR","Amber Road Inc","-0.44","--","--","--","14.2569");
INSERT INTO stox.earnings_growth values ("AMRH","Ameri Holdings Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("ANGI","Angie's List","-0.13","0.06","0.26","--","29.1335");
INSERT INTO stox.earnings_growth values ("APPF","AppFolio Inc","-0.12","--","--","--","--");
INSERT INTO stox.earnings_growth values ("APTI","Apptio","-1.08","--","0.01","--","--");
INSERT INTO stox.earnings_growth values ("ASTI","Ascent Solar Technologies Inc","--","--","--","--","-15.0509");
INSERT INTO stox.earnings_growth values ("ASUR","Asure Software Inc","0.24","--","--","-26.611","26.5718");
INSERT INTO stox.earnings_growth values ("ASYS","Amtech Systems Inc","-0.53","--","--","96.393","-13.379");
INSERT INTO stox.earnings_growth values ("ATEN","A10 Networks, Inc.","-0.04","0.12","0.31","--","20.3022");
INSERT INTO stox.earnings_growth values ("ATOM","Atomera Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("AVID","Avid Technology Inc","1.9","--","--","45.411","-5.4624");
INSERT INTO stox.earnings_growth values ("AVNW","Aviat Networks Inc","--","--","--","--","-9.8837");
INSERT INTO stox.earnings_growth values ("AYX","Alteryx Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("BBOX","Black Box Corp","1.11","--","--","-24.244","-3.099");
INSERT INTO stox.earnings_growth values ("BCOR","Blucora Inc","1.06","--","--","34.35","14.7836");
INSERT INTO stox.earnings_growth values ("BCOV","Brightcove Inc","0","--","--","--","18.7767");
INSERT INTO stox.earnings_growth values ("BELFB","Bel Fuse Inc","--","--","--","41.996","11.1272");
INSERT INTO stox.earnings_growth values ("BITA","Bitauto","3.28","--","--","-5.277","52.8762");
INSERT INTO stox.earnings_growth values ("BL","Blackline Inc","-0.39","--","--","--","--");
INSERT INTO stox.earnings_growth values ("BLIN","Bridgeline Digital Inc","-0.75","--","--","--","-9.558");
INSERT INTO stox.earnings_growth values ("BNFT","Benefitfocus Inc","-0.73","--","--","--","27.6732");
INSERT INTO stox.earnings_growth values ("BOX","Box","-0.56","--","--","--","80.0188");
INSERT INTO stox.earnings_growth values ("BSFT","BroadSoft Inc","2.3","--","--","15.349","19.8188");
INSERT INTO stox.earnings_growth values ("BSQR","Bsquare Corp","--","--","--","--","0.1232");
INSERT INTO stox.earnings_growth values ("BV","Bazaarvoice Inc","-0.05","--","--","--","25.3766");
INSERT INTO stox.earnings_growth values ("BVSN","BroadVision Inc","--","--","--","--","-14.6725");
INSERT INTO stox.earnings_growth values ("CALD","Callidus Software Inc","0.28","--","--","39.58","19.8");
INSERT INTO stox.earnings_growth values ("CALX","Calix Inc","-0.14","--","--","34.777","5.8868");
INSERT INTO stox.earnings_growth values ("CAMP","CalAmp Corp","1.06","--","--","23.949","20.4076");
INSERT INTO stox.earnings_growth values ("CARB","Carbonite Inc","0.6","--","--","--","27.8851");
INSERT INTO stox.earnings_growth values ("CAVM","Cavium","1.53","2.73","3.62","42.903","18.4077");
INSERT INTO stox.earnings_growth values ("CBAK","CBAK Energy Technology Inc","--","--","--","--","-42.301");
INSERT INTO stox.earnings_growth values ("CBRIQ","Ciber Inc","--","--","--","-1.091","-5.9835");
INSERT INTO stox.earnings_growth values ("CCIH","ChinaCache International Holdings Ltd","--","--","--","--","10.5605");
INSERT INTO stox.earnings_growth values ("CCUR","Concurrent Computer Corp","--","--","--","--","-1.7523");
INSERT INTO stox.earnings_growth values ("CDRB","Code Rebel Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("CLDR","Cloudera Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("CLIR","ClearSign Combustion Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("CLOK","Cipherloc Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("CMCM","Cheetah Mobile Inc","2.26","--","--","14.925","99.4765");
INSERT INTO stox.earnings_growth values ("CMTL","Comtech Telecommunications Corp","-0.46","--","--","-24.674","-7.6653");
INSERT INTO stox.earnings_growth values ("CNDT","Conduent Inc","1.06","--","--","--","0.4236");
INSERT INTO stox.earnings_growth values ("CNIT","China Information Technology Inc","--","--","--","--","-42.5152");
INSERT INTO stox.earnings_growth values ("CNTF","China Techfaith Wireless Communication Technology Ltd","--","--","--","--","-24.9788");
INSERT INTO stox.earnings_growth values ("COOL","Polarityte Inc","--","--","--","--","-58.5014");
INSERT INTO stox.earnings_growth values ("COUP","Coupa Software Inc","-1.36","--","--","--","--");
INSERT INTO stox.earnings_growth values ("COVS","Covisint Corp","--","--","--","--","7.0198");
INSERT INTO stox.earnings_growth values ("CPAH","CounterPath Corp","-0.39","--","--","--","0.0743");
INSERT INTO stox.earnings_growth values ("CRAY","Cray Inc","0.49","--","--","19.753","21.6865");
INSERT INTO stox.earnings_growth values ("CRCM","Care.com","0.19","0.4","0.47","--","44.1306");
INSERT INTO stox.earnings_growth values ("CRDS","Crossroads Systems Inc","--","--","--","--","-46.2239");
INSERT INTO stox.earnings_growth values ("CREE","CREE","0.86","0.41","1.21","-15.233","10.3581");
INSERT INTO stox.earnings_growth values ("CRTN","Cartesian Inc","--","--","--","--","2.6034");
INSERT INTO stox.earnings_growth values ("CSIQ","Canadian Solar Inc","1.6","--","--","-4.935","8.4829");
INSERT INTO stox.earnings_growth values ("CSOD","Cornerstone OnDemand, Inc.","0.11","0.42","0.85","--","42.1029");
INSERT INTO stox.earnings_growth values ("CSUNY","China Sunergy Co Ltd","--","--","--","--","-3.1018");
INSERT INTO stox.earnings_growth values ("CTG","Computer Task Group Inc","0.23","--","--","-29.746","-3.8944");
INSERT INTO stox.earnings_growth values ("CUI","CUI Global Inc","-0.35","--","--","--","17.2975");
INSERT INTO stox.earnings_growth values ("CVV","CVD Equipment Corp","--","--","--","--","-7.5294");
INSERT INTO stox.earnings_growth values ("CY","Cypress Semiconductor","0.49","0.7","1.1","5.816","14.0823");
INSERT INTO stox.earnings_growth values ("CYOU","Changyou.com Limited","2.85","3.3165","3.5972","-12.332","1.6303");
INSERT INTO stox.earnings_growth values ("DATA","Tableau Software, Inc.","0.43","0.01","0.17","70.248","67.6926");
INSERT INTO stox.earnings_growth values ("DBD","Diebold Nixdorf Inc","1.06","--","--","-8.394","3.1797");
INSERT INTO stox.earnings_growth values ("DDD","3D Systems Corporation","0.46","0.54","0.73","-17.854","22.397");
INSERT INTO stox.earnings_growth values ("DGLT","Digiliti Money Group Inc","-1.24","--","--","--","--");
INSERT INTO stox.earnings_growth values ("DGLY","Digital Ally Inc","-2.38","--","--","--","-3.2751");
INSERT INTO stox.earnings_growth values ("DHX","DHI Group Inc","0.39","--","--","-8.437","4.848");
INSERT INTO stox.earnings_growth values ("DMRC","Digimarc Corp","-2.36","--","--","42.701","-9.5708");
INSERT INTO stox.earnings_growth values ("DQ","Daqo New Energy Corp","4.11","--","--","-24.45","-2.183");
INSERT INTO stox.earnings_growth values ("DRAM","Dataram Corp","--","--","--","--","-11.6754");
INSERT INTO stox.earnings_growth values ("DST","DST Systems","5.73","6.56","7.41","12.193","-8.1803");
INSERT INTO stox.earnings_growth values ("DTRM","Determine Inc","-0.65","--","--","--","7.4932");
INSERT INTO stox.earnings_growth values ("DWCH","Datawatch Corp","-0.66","--","--","-9.055","11.2382");
INSERT INTO stox.earnings_growth values ("DYSL","Dynasil Corporation of America","--","--","--","--","-1.5418");
INSERT INTO stox.earnings_growth values ("ECOM","ChannelAdvisor Corp","0.2","--","--","--","21.0408");
INSERT INTO stox.earnings_growth values ("EDGW","Edgewater Technology Inc","0.09","--","--","-3.428","4.3126");
INSERT INTO stox.earnings_growth values ("EGAN","eGain Corp","-0.23","--","--","--","9.502");
INSERT INTO stox.earnings_growth values ("EGHT","EGHT","0.16","0.2","0.24","2.524","24.4363");
INSERT INTO stox.earnings_growth values ("EIGI","Endurance International Group Holdings Inc","-0.55","--","--","28.839","42.319");
INSERT INTO stox.earnings_growth values ("ELON","Echelon Corp","--","--","--","--","-27.0252");
INSERT INTO stox.earnings_growth values ("ENOC","EnerNOC Inc","-1.72","--","--","8.301","7.105");
INSERT INTO stox.earnings_growth values ("ENV","Envestnet Inc","0.98","--","--","30.686","36.2397");
INSERT INTO stox.earnings_growth values ("EPAY","Bottomline Technologies (DE) Inc","1.52","--","--","1.677","12.6318");
INSERT INTO stox.earnings_growth values ("ESIO","Electro Scientific Industries Inc","-0.05","--","--","-38.763","-6.4109");
INSERT INTO stox.earnings_growth values ("EVRI","Everi Holdings Inc","-1.49","--","--","0.148","9.5759");
INSERT INTO stox.earnings_growth values ("EXA","Exa Corp","0.03","--","--","-22.182","9.5975");
INSERT INTO stox.earnings_growth values ("EXAR","Exar Corp","0.31","--","--","16.262","0.4578");
INSERT INTO stox.earnings_growth values ("EXTR","Extreme Networks Inc","0.28","--","--","12.081","9.5797");
INSERT INTO stox.earnings_growth values ("FALC","FalconStor Software Inc","--","--","--","--","-18.2471");
INSERT INTO stox.earnings_growth values ("FEYE","FireEye Inc.","-0.99","--","--","--","84.2196");
INSERT INTO stox.earnings_growth values ("FIT","Fitbit","-0.12","--","--","--","--");
INSERT INTO stox.earnings_growth values ("FIVN","Five9, Inc","-0.07","--","0.04","--","30.2803");
INSERT INTO stox.earnings_growth values ("FNJN","Finjan Holdings Inc","-0.28","--","--","--","42.2922");
INSERT INTO stox.earnings_growth values ("FORTY","Formula Systems 1985 Ltd","--","--","--","--","6.4271");
INSERT INTO stox.earnings_growth values ("FRTN","Fortran Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("FSLR","First Solar, Inc.","5.17","0.57","0.74","3.992","1.304");
INSERT INTO stox.earnings_growth values ("FTEO","FRONTEO Inc","-0.03","--","--","--","22.4823");
INSERT INTO stox.earnings_growth values ("FUEL","Rocket Fuel Inc","-0.59","--","--","--","59.175");
INSERT INTO stox.earnings_growth values ("GIGA","Giga-tronics Inc","--","--","--","--","-7.0428");
INSERT INTO stox.earnings_growth values ("GLA","Glassbridge Enterprises Inc","--","--","--","--","-49.0971");
INSERT INTO stox.earnings_growth values ("GLUU","Glu Mobile Inc","-0.31","--","--","--","24.8263");
INSERT INTO stox.earnings_growth values ("GOGO","Gogo Inc","-1.58","--","--","--","30.083");
INSERT INTO stox.earnings_growth values ("GRVY","Gravity Co Ltd","--","--","--","--","-10.3619");
INSERT INTO stox.earnings_growth values ("GSUM","Gridsum Holding Inc","-5.76","--","--","--","--");
INSERT INTO stox.earnings_growth values ("GUID","Guidance Software Inc","-0.05","--","--","--","1.1066");
INSERT INTO stox.earnings_growth values ("HAUP","Hauppauge Digital Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("HAWK","Blackhawk Network Holdings Inc.","1.43","1.64","1.99","25.551","20.3703");
INSERT INTO stox.earnings_growth values ("HDP","Hortonworks Inc","-2.58","--","--","--","--");
INSERT INTO stox.earnings_growth values ("HIVE","Aerohive Networks","-0.25","--","0.09","--","37.9803");
INSERT INTO stox.earnings_growth values ("HLIT","Harmonic Inc","-0.04","--","--","-13.123","-5.8719");
INSERT INTO stox.earnings_growth values ("HMNY","Helios and Matheson Analytics Inc","--","--","--","--","-11.1443");
INSERT INTO stox.earnings_growth values ("HOLI","Hollysys Automation Technologies Ltd","2.02","--","--","10.683","15.6732");
INSERT INTO stox.earnings_growth values ("HQCL","Hanwha Q Cells Co Ltd","1.45","--","--","36.26","19.5137");
INSERT INTO stox.earnings_growth values ("HUBS","HubSpot, Inc.","-0.36","--","0.29","--","56.8386");
INSERT INTO stox.earnings_growth values ("IAIC","Information Analysis Inc","--","--","--","--","-2.963");
INSERT INTO stox.earnings_growth values ("IDCC","InterDigital Inc","8.78","--","--","30.069","17.1517");
INSERT INTO stox.earnings_growth values ("IDSY","ID Systems Inc","-0.22","--","--","48.324","-1.2901");
INSERT INTO stox.earnings_growth values ("IGOI","iGO Inc","--","--","--","--","-63.1426");
INSERT INTO stox.earnings_growth values ("III","Information Services Group Inc","--","--","--","--","3.2587");
INSERT INTO stox.earnings_growth values ("IIN","IntriCon Corp","-0.26","--","--","8.51","3.9407");
INSERT INTO stox.earnings_growth values ("IMI","Intermolecular Inc","-0.24","--","--","--","-2.5541");
INSERT INTO stox.earnings_growth values ("IMMR","Immersion Corp","-0.17","--","--","54.44","13.2563");
INSERT INTO stox.earnings_growth values ("IMPV","Imperva Inc","-0.07","--","--","--","27.5604");
INSERT INTO stox.earnings_growth values ("INAP","Internap Corp","-0.52","--","--","-15.91","4.0468");
INSERT INTO stox.earnings_growth values ("INFN","Infinera Corp","0.34","--","--","27.907","16.534");
INSERT INTO stox.earnings_growth values ("INOD","Innodata Inc","--","--","--","--","-3.1294");
INSERT INTO stox.earnings_growth values ("INPHQ","Interphase Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("INSE","Inspired Entertainment Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("INSG","Inseego Corp","-0.23","--","--","77.658","-8.2026");
INSERT INTO stox.earnings_growth values ("INST","Instructure Inc","-1.55","--","--","--","--");
INSERT INTO stox.earnings_growth values ("INVE","Identiv Inc","-1.25","--","--","-40.391","-11.3708");
INSERT INTO stox.earnings_growth values ("INVN","InvenSense Inc","0.49","--","--","-15.359","34.0817");
INSERT INTO stox.earnings_growth values ("INVT","Inventergy Global Inc","--","--","--","--","-40.3083");
INSERT INTO stox.earnings_growth values ("INVU","Investview Inc","--","--","--","--","-29.3591");
INSERT INTO stox.earnings_growth values ("IOTS","Adesto Technologies Corp","-0.6","--","--","--","--");
INSERT INTO stox.earnings_growth values ("IPAS","iPass Inc","-0.12","--","--","29.099","-14.7926");
INSERT INTO stox.earnings_growth values ("IPDN","Professional Diversity Network Inc","--","--","--","--","36.3293");
INSERT INTO stox.earnings_growth values ("JASO","JA Solar Holdings Co Ltd","1.9","--","--","38.496","7.2779");
INSERT INTO stox.earnings_growth values ("JCS","Communications Systems Inc","--","--","--","-35.164","-7.1249");
INSERT INTO stox.earnings_growth values ("JIVE","Jive Software Inc","0.1","--","--","--","21.4359");
INSERT INTO stox.earnings_growth values ("JKS","JinkoSolar Holding Co Ltd","4.72","--","--","43.805","22.9377");
INSERT INTO stox.earnings_growth values ("JMU","JMU Ltd","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("JTPY","JetPay Corp","-0.52","--","--","--","--");
INSERT INTO stox.earnings_growth values ("KEM","KEMET Corp","0.17","--","--","29.23","-6.3203");
INSERT INTO stox.earnings_growth values ("KN","Knowles Corp","0.94","--","--","-3.535","-2.6603");
INSERT INTO stox.earnings_growth values ("KONE","Kingtone Wirelessinfo Solution Holding Ltd","--","--","--","--","-28.6132");
INSERT INTO stox.earnings_growth values ("KOPN","Kopin Corp","-0.38","--","--","-50.87","-29.6223");
INSERT INTO stox.earnings_growth values ("KTCC","Key Tronic Corp","--","--","--","--","13.8225");
INSERT INTO stox.earnings_growth values ("KVHI","KVH Industries Inc","0.44","--","--","11.775","9.3716");
INSERT INTO stox.earnings_growth values ("LDKYQ","LDK Solar Co Ltd","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("LEJU","Leju","0.07","--","0.2466","-67.916","32.483");
INSERT INTO stox.earnings_growth values ("LFGR","Leaf Group Ltd","-0.91","--","--","-57.904","-18.9745");
INSERT INTO stox.earnings_growth values ("LLNW","Limelight Networks Inc","0.01","--","--","--","-0.3596");
INSERT INTO stox.earnings_growth values ("LOCMQ","Local Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("LPSN","LivePerson Inc","-0.14","--","--","-21.234","10.8527");
INSERT INTO stox.earnings_growth values ("LQDT","Liquidity Services Inc","-0.02","--","--","-40.555","-0.6765");
INSERT INTO stox.earnings_growth values ("LRAD","LRAD Corp","--","--","--","--","-9.199");
INSERT INTO stox.earnings_growth values ("LSCC","Lattice Semiconductor Corp","0.14","--","--","-9.483","6.0501");
INSERT INTO stox.earnings_growth values ("LTRX","Lantronix Inc","-0.13","--","--","--","-3.8207");
INSERT INTO stox.earnings_growth values ("LUNA","Luna Innovations Inc","-0.09","--","--","--","10.7024");
INSERT INTO stox.earnings_growth values ("MARK","Remark Holdings Inc","-1.54","--","--","--","64.0583");
INSERT INTO stox.earnings_growth values ("MATR","Mattersight Corp","-0.86","--","--","--","7.668");
INSERT INTO stox.earnings_growth values ("MB","Mindbody Inc","-0.35","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MCHX","Marchex Inc","-0.16","--","--","-13.128","-2.4597");
INSERT INTO stox.earnings_growth values ("MJCO","Majesco","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MLNK","ModusLink Global Solutions Inc","--","--","--","--","-12.1342");
INSERT INTO stox.earnings_growth values ("MOBL","MobileIron Inc","-0.36","--","--","--","63.9087");
INSERT INTO stox.earnings_growth values ("MODN","Model N Inc","-0.64","--","--","--","10.4186");
INSERT INTO stox.earnings_growth values ("MOSY","MoSys Inc","-2.92","--","--","-62.732","-15.649");
INSERT INTO stox.earnings_growth values ("MRAM","Everspin Technologies Inc","-3.52","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MRIN","Marin Software Inc","--","--","--","--","22.5581");
INSERT INTO stox.earnings_growth values ("MSDI","Monster Digital Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MTLS","Materialise NV","-0.06","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MTSI","M/A-Com","1.91","2.64","3.02","22.882","11.8971");
INSERT INTO stox.earnings_growth values ("MTWO","M2 Ngage Group Inc","--","--","--","--","18.7402");
INSERT INTO stox.earnings_growth values ("MULE","MuleSoft Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("MVIS","MicroVision Inc","-0.32","--","--","--","21.3172");
INSERT INTO stox.earnings_growth values ("MX","MagnaChip Semiconductor Corp","-0.13","--","--","-10.442","-3.9501");
INSERT INTO stox.earnings_growth values ("MXPT","MaxPoint Interactive Inc","-2.04","--","--","--","58.9869");
INSERT INTO stox.earnings_growth values ("MXWL","Maxwell Technologies Inc","-0.68","--","--","--","-5.0751");
INSERT INTO stox.earnings_growth values ("NAME","Rightside Group Ltd","-1.51","--","--","--","-17.2876");
INSERT INTO stox.earnings_growth values ("NCTY","The9 Ltd","--","--","--","--","-12.5326");
INSERT INTO stox.earnings_growth values ("NEON","Neonode Inc","-0.12","--","--","18.696","10.9777");
INSERT INTO stox.earnings_growth values ("NETE","Net Element Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("NEWR","New Relic Inc","-0.85","--","--","--","--");
INSERT INTO stox.earnings_growth values ("NLST","Netlist Inc","-0.21","--","--","--","-26.7599");
INSERT INTO stox.earnings_growth values ("NMRX","Numerex Corp","-1.25","--","--","-24.971","3.8947");
INSERT INTO stox.earnings_growth values ("NPTN","NeoPhotonics Corp","0.5","--","--","11.487","15.4");
INSERT INTO stox.earnings_growth values ("NQ","NQ Mobile Inc","--","--","--","--","53.1844");
INSERT INTO stox.earnings_growth values ("NSR","Neustar Inc","5.69","--","--","24.186","14.2889");
INSERT INTO stox.earnings_growth values ("NTNX","Nutanix Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("NUAN","Nuance Communications Inc","1.52","--","--","-1.261","8.125");
INSERT INTO stox.earnings_growth values ("NXES","Nexus Enterprise Solutions Inc","--","--","--","--","109.9687");
INSERT INTO stox.earnings_growth values ("OCC","Optical Cable Corp","--","--","--","--","-2.501");
INSERT INTO stox.earnings_growth values ("OCLR","Oclaro Inc","0.17","--","--","--","-2.6485");
INSERT INTO stox.earnings_growth values ("OIIM","O2micro International Ltd","-0.12","--","--","-19.019","-14.5679");
INSERT INTO stox.earnings_growth values ("OKTA","Okta Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("ONSM","Onstream Media Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("ONVI","Onvia Inc","--","--","--","--","1.1836");
INSERT INTO stox.earnings_growth values ("P","Pandora Media, Inc.","-0.51","--","--","22.474","38.236");
INSERT INTO stox.earnings_growth values ("PAY","Verifone Systems Inc","1.66","--","--","-9.656","8.8473");
INSERT INTO stox.earnings_growth values ("PCMI","PCM Inc","1.4","--","--","33.244","9.1122");
INSERT INTO stox.earnings_growth values ("PCTI","PCTEL Inc","0.2","--","--","-5.693","4.7068");
INSERT INTO stox.earnings_growth values ("PCTY","Paylocity Corp.","0.3","0.58","0.87","--","42.8111");
INSERT INTO stox.earnings_growth values ("PFPT","Proofpoint Inc","0.37","--","--","--","35.622");
INSERT INTO stox.earnings_growth values ("PFSW","PFSweb Inc","0.11","--","--","--","2.294");
INSERT INTO stox.earnings_growth values ("PI","Impinj Inc","0.22","--","--","--","--");
INSERT INTO stox.earnings_growth values ("PLPM","Planet Payment Inc","0.16","--","--","52.765","5.3571");
INSERT INTO stox.earnings_growth values ("PRCP","Perceptron Inc","-0.32","--","--","-6.907","3.1267");
INSERT INTO stox.earnings_growth values ("PRGS","Progress Software Corp","1.65","--","--","12.405","-5.3498");
INSERT INTO stox.earnings_growth values ("PRGX","PRGX Global Inc","0.04","--","--","-23.123","-7.0609");
INSERT INTO stox.earnings_growth values ("PRKR","ParkerVision Inc","-1.76","--","--","--","--");
INSERT INTO stox.earnings_growth values ("PRO","PROS Holdings Inc","-0.92","--","--","-8.68","9.6641");
INSERT INTO stox.earnings_growth values ("PSDO","Presidio Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("PSTG","Pure Storage","-0.5","--","0.2","--","--");
INSERT INTO stox.earnings_growth values ("QADB","QAD Inc","--","--","--","--","2.3695");
INSERT INTO stox.earnings_growth values ("QBAK","Qualstar Corp","--","--","--","--","-12.4446");
INSERT INTO stox.earnings_growth values ("QNST","Quinstreet Inc","0.02","--","--","-49.613","-5.8778");
INSERT INTO stox.earnings_growth values ("QTM","Quantum Corp","-0.08","--","--","-11.093","-6.6735");
INSERT INTO stox.earnings_growth values ("QTWO","Q2 Holdings Inc","-0.32","--","--","--","40.9721");
INSERT INTO stox.earnings_growth values ("QUIK","QuickLogic Corp","-0.26","--","--","--","-11.4425");
INSERT INTO stox.earnings_growth values ("QUMU","Qumu Corp","-1.23","--","--","-27.33","-17.6458");
INSERT INTO stox.earnings_growth values ("QUOT","Quotient Technology Inc","0.12","0.28","0.44","15.47","24.6834");
INSERT INTO stox.earnings_growth values ("RATE","Bankrate","0.61","0.7","0.8","3.584","0.4653");
INSERT INTO stox.earnings_growth values ("RBCN","Rubicon Technology Inc","--","--","--","--","-31.8975");
INSERT INTO stox.earnings_growth values ("REDFY","Rediff.com India Ltd","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("REFR","Research Frontiers Inc","-0.18","--","--","--","7.8793");
INSERT INTO stox.earnings_growth values ("RELL","Richardson Electronics Ltd","-0.14","--","--","-52.72","-2.2176");
INSERT INTO stox.earnings_growth values ("RESN","Resonant Inc","-1.57","--","--","--","--");
INSERT INTO stox.earnings_growth values ("RFIL","RF Industries Ltd","--","--","--","--","9.2469");
INSERT INTO stox.earnings_growth values ("RMGN","RMG Networks Holding Corp","-0.13","--","--","--","--");
INSERT INTO stox.earnings_growth values ("RNG","RNG","0.09","0.16","0.26","--","36.9315");
INSERT INTO stox.earnings_growth values ("RNWK","RealNetworks Inc","-0.99","--","--","-48.87","-18.5319");
INSERT INTO stox.earnings_growth values ("RPD","Rapid7 Inc","-0.71","--","--","--","--");
INSERT INTO stox.earnings_growth values ("RST","Rosetta Stone Inc","-1.25","--","--","--","-6.281");
INSERT INTO stox.earnings_growth values ("RSYS","Radisys Corp","0.25","--","--","0.322","-8.4839");
INSERT INTO stox.earnings_growth values ("RUBI","Rubicon Project Inc","1.14","--","--","--","49.6578");
INSERT INTO stox.earnings_growth values ("SALE","RetailMeNot Inc","0.69","--","--","-14.062","28.3834");
INSERT INTO stox.earnings_growth values ("SANM","Sanmina","2.54","1.91","2.15","21.338","-0.37");
INSERT INTO stox.earnings_growth values ("SCKT","Socket Mobile Inc","--","--","--","--","3.4903");
INSERT INTO stox.earnings_growth values ("SCON","Superconductor Technologies Inc","-3.53","--","--","--","-48.1599");
INSERT INTO stox.earnings_growth values ("SCOR","Comscore Inc","-0.18","--","--","-57.21","16.0794");
INSERT INTO stox.earnings_growth values ("SCWX","SecureWorks","-0.19","--","0.04","--","--");
INSERT INTO stox.earnings_growth values ("SEAC","SeaChange International Inc","-0.6","--","--","-26.279","-15.7752");
INSERT INTO stox.earnings_growth values ("SFUN","Soufun Holdings Ltd-ADR","-0.37","--","0.1824","-3.198","21.6602");
INSERT INTO stox.earnings_growth values ("SHOR","Shoretel Inc","0.18","--","--","-28.021","12.4798");
INSERT INTO stox.earnings_growth values ("SIGM","Sigma Designs Inc","-0.11","--","--","28.667","3.8463");
INSERT INTO stox.earnings_growth values ("SIMO","Silicon Motion Technology Corporation","3.64","2.1635","1.7072","24.635","19.8914");
INSERT INTO stox.earnings_growth values ("SMIT","Schmitt Industries Inc","--","--","--","--","0.3328");
INSERT INTO stox.earnings_growth values ("SMSI","Smith Micro Software Inc","--","--","--","--","-13.3394");
INSERT INTO stox.earnings_growth values ("SMTX","SMTC Corp","--","--","--","--","-5.2955");
INSERT INTO stox.earnings_growth values ("SOL","ReneSola Ltd","-1.5","--","--","-9.665","-1.1516");
INSERT INTO stox.earnings_growth values ("SONS","Sonus Networks Inc","0.33","--","--","16.708","-0.5533");
INSERT INTO stox.earnings_growth values ("SPDC","Speed Commerce Inc","--","--","--","-8.234","--");
INSERT INTO stox.earnings_growth values ("SPWR","SunPower Corp. - Class A","-0.46","--","--","40.41","1.7842");
INSERT INTO stox.earnings_growth values ("SQNS","Sequans Communications SA","-0.31","--","--","--","-13.4251");
INSERT INTO stox.earnings_growth values ("SREV","ServiceSource International Inc","0.04","--","--","-11.478","4.2372");
INSERT INTO stox.earnings_growth values ("SSNI","Silver Spring Networks Inc","0.24","--","--","--","5.5811");
INSERT INTO stox.earnings_growth values ("SSYS","Stratasys Ltd.","0.28","0.25","0.45","-38.37","33.9575");
INSERT INTO stox.earnings_growth values ("STRI","STR Holdings Inc","--","--","--","--","-38.704");
INSERT INTO stox.earnings_growth values ("SUNEQ","SunEdison Inc","-0.96","--","--","6.458","--");
INSERT INTO stox.earnings_growth values ("SYNC","Synacor Inc","-0.36","--","--","--","6.9424");
INSERT INTO stox.earnings_growth values ("SYNT","Syntel Inc","-0.68","--","--","2.445","8.5134");
INSERT INTO stox.earnings_growth values ("SYX","Systemax Inc","0.22","--","--","-27.107","-14.523");
INSERT INTO stox.earnings_growth values ("TAIT","Taitron Components Inc","--","--","--","--","0.3242");
INSERT INTO stox.earnings_growth values ("TCCO","Technical Communications Corp","--","--","--","--","-26.9182");
INSERT INTO stox.earnings_growth values ("TIGR","TigerLogic Corp","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("TNAV","Telenav Inc","-0.58","--","--","-41.422","-2.7236");
INSERT INTO stox.earnings_growth values ("TNGO","Tangoe Inc","0.7","--","--","6.015","--");
INSERT INTO stox.earnings_growth values ("TRMR","Tremor Video Inc","-0.4","--","--","--","13.0526");
INSERT INTO stox.earnings_growth values ("TRUE","TrueCar Inc","-0.13","--","--","--","29.4541");
INSERT INTO stox.earnings_growth values ("TRVG","Trivago","0.07","0.05","0.22","--","--");
INSERT INTO stox.earnings_growth values ("TTD","Trade Desk Inc","0.89","--","--","--","--");
INSERT INTO stox.earnings_growth values ("TWLO","Twilio Inc","-0.16","--","--","--","--");
INSERT INTO stox.earnings_growth values ("TWOU","2U Inc","-0.1","--","--","--","47.2544");
INSERT INTO stox.earnings_growth values ("UCTT","Ultra Clean Holdings Inc","0.65","--","--","16.064","--");
INSERT INTO stox.earnings_growth values ("UIS","Unisys Corp","-0.95","--","--","-30.593","-6.0507");
INSERT INTO stox.earnings_growth values ("UNXL","Uni-Pixel Inc","-0.71","--","--","--","83.8418");
INSERT INTO stox.earnings_growth values ("UPLD","Upland Software Inc","-0.82","--","--","--","--");
INSERT INTO stox.earnings_growth values ("USAT","USA Technologies Inc","-0.01","--","--","--","27.617");
INSERT INTO stox.earnings_growth values ("VECO","Veeco Instruments","-0.29","0.76","1.22","-38.183","-19.4293");
INSERT INTO stox.earnings_growth values ("VIDE","Video Display Corp","--","--","--","--","-27.7516");
INSERT INTO stox.earnings_growth values ("VNET","21Vianet Group Inc","-2.4","--","--","-44.729","28.1542");
INSERT INTO stox.earnings_growth values ("VRNS","Varonis Systems Inc","-0.17","--","--","--","32.8248");
INSERT INTO stox.earnings_growth values ("VRNT","Verint Systems Inc","2.51","--","--","1.637","6.2968");
INSERT INTO stox.earnings_growth values ("WK","Workiva Inc","-0.73","--","--","--","64.4264");
INSERT INTO stox.earnings_growth values ("WPCS","WPCS International Inc","--","--","--","--","-31.5466");
INSERT INTO stox.earnings_growth values ("WSTL","Westell Technologies Inc","-0.14","--","--","-10.518","-14.2439");
INSERT INTO stox.earnings_growth values ("XCOMQ","Xtera Communications Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("XGTI","xG Technology Inc","-32.51","--","--","--","112.9844");
INSERT INTO stox.earnings_growth values ("XNET","Xunlei Ltd","--","--","--","--","26.5177");
INSERT INTO stox.earnings_growth values ("XTLY","Xactly Corp","-0.28","--","--","--","--");
INSERT INTO stox.earnings_growth values ("YELP","Yelp","-0.06","0.99","1.28","--","53.6431");
INSERT INTO stox.earnings_growth values ("YEXT","Yext Inc","--","--","--","--","--");
INSERT INTO stox.earnings_growth values ("YGE","Yingli Green Energy Holding Co Ltd","-6.08","--","--","-30.139","-11.1731");
INSERT INTO stox.earnings_growth values ("YRD","Yirendai Ltd","2.74","--","--","--","--");
INSERT INTO stox.earnings_growth values ("YUME","YuMe Inc","--","--","--","--","18.5295");
INSERT INTO stox.earnings_growth values ("YY","YY","28.98","30.4691","36.6108","54.64","90.1686");
INSERT INTO stox.earnings_growth values ("ZBRA","Zebra Technologies Corp","5.6","--","--","25.515","29.3334");
INSERT INTO stox.earnings_growth values ("ZEN","Zendesk, Inc.","-0.22","--","--","--","82.061");
INSERT INTO stox.earnings_growth values ("ZG","Zillow","-0.5","0.4","0.96","38.196","66.5544");
INSERT INTO stox.earnings_growth values ("ZNGA","ZYNGA","0.03","0.09","0.1","-30.064","-8.2462");
