INSERT INTO stox.ratings values ("ACFN","Acorn Energy Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ACIA","Acacia Communications","1","C","9","--","--");
INSERT INTO stox.ratings values ("ACTA","Actua Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("AEHR","AEHR Test Systems","--","--","--","--","--");
INSERT INTO stox.ratings values ("AGYS","Agilysys Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("AIXNY","Aixtron SE","--","--","--","--","--");
INSERT INTO stox.ratings values ("AMBR","Amber Road Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("AMRH","Ameri Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ANGI","Angie's List","--","--","--","--","--");
INSERT INTO stox.ratings values ("APPF","AppFolio Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("APTI","Apptio","1","C","9","--","--");
INSERT INTO stox.ratings values ("ASTI","Ascent Solar Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ASUR","Asure Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ASYS","Amtech Systems Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ATEN","A10 Networks, Inc.","1","C","9","--","--");
INSERT INTO stox.ratings values ("ATOM","Atomera Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("AVID","Avid Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("AVNW","Aviat Networks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("AYX","Alteryx Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BBOX","Black Box Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("BCOR","Blucora Inc","--","--","--","--","4");
INSERT INTO stox.ratings values ("BCOV","Brightcove Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BELFB","Bel Fuse Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BITA","Bitauto","1","C","9","--","--");
INSERT INTO stox.ratings values ("BL","Blackline Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BLIN","Bridgeline Digital Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BNFT","Benefitfocus Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BOX","Box","1","B","9","--","--");
INSERT INTO stox.ratings values ("BSFT","BroadSoft Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BSQR","Bsquare Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("BV","Bazaarvoice Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("BVSN","BroadVision Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CALD","Callidus Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CALX","Calix Inc","--","--","--","3","--");
INSERT INTO stox.ratings values ("CAMP","CalAmp Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CARB","Carbonite Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CAVM","Cavium","1","B","9","3","3");
INSERT INTO stox.ratings values ("CBAK","CBAK Energy Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CBRIQ","Ciber Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CCIH","ChinaCache International Holdings Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("CCUR","Concurrent Computer Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CDRB","Code Rebel Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CLDR","Cloudera Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CLIR","ClearSign Combustion Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CLOK","Cipherloc Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CMCM","Cheetah Mobile Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CMTL","Comtech Telecommunications Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CNDT","Conduent Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CNIT","China Information Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CNTF","China Techfaith Wireless Communication Technology Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("COOL","Polarityte Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("COUP","Coupa Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("COVS","Covisint Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CPAH","CounterPath Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CRAY","Cray Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CRCM","Care.com","3","C","9","--","--");
INSERT INTO stox.ratings values ("CRDS","Crossroads Systems Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CREE","CREE","2","C","9","--","3");
INSERT INTO stox.ratings values ("CRTN","Cartesian Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CSIQ","Canadian Solar Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CSOD","Cornerstone OnDemand, Inc.","2","B","9","--","--");
INSERT INTO stox.ratings values ("CSUNY","China Sunergy Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("CTG","Computer Task Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CUI","CUI Global Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("CVV","CVD Equipment Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("CY","Cypress Semiconductor","1","B","7","3","4");
INSERT INTO stox.ratings values ("CYOU","Changyou.com Limited","3","C","9","--","--");
INSERT INTO stox.ratings values ("DATA","Tableau Software, Inc.","1","C","9","3","--");
INSERT INTO stox.ratings values ("DBD","Diebold Nixdorf Inc","--","--","--","--","3");
INSERT INTO stox.ratings values ("DDD","3D Systems Corporation","1","C","9","3","3");
INSERT INTO stox.ratings values ("DGLT","Digiliti Money Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("DGLY","Digital Ally Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("DHX","DHI Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("DMRC","Digimarc Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("DQ","Daqo New Energy Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("DRAM","Dataram Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("DST","DST Systems","1","B","7","--","--");
INSERT INTO stox.ratings values ("DTRM","Determine Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("DWCH","Datawatch Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("DYSL","Dynasil Corporation of America","--","--","--","--","--");
INSERT INTO stox.ratings values ("ECOM","ChannelAdvisor Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("EDGW","Edgewater Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("EGAN","eGain Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("EGHT","EGHT","1","C","9","--","--");
INSERT INTO stox.ratings values ("EIGI","Endurance International Group Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ELON","Echelon Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("ENOC","EnerNOC Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ENV","Envestnet Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("EPAY","Bottomline Technologies (DE) Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ESIO","Electro Scientific Industries Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("EVRI","Everi Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("EXA","Exa Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("EXAR","Exar Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("EXTR","Extreme Networks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("FALC","FalconStor Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("FEYE","FireEye Inc.","1","C","9","2","3");
INSERT INTO stox.ratings values ("FIT","Fitbit","3","C","9","--","4");
INSERT INTO stox.ratings values ("FIVN","Five9, Inc","3","C","9","--","--");
INSERT INTO stox.ratings values ("FNJN","Finjan Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("FORTY","Formula Systems 1985 Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("FRTN","Fortran Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("FSLR","First Solar, Inc.","1","C","9","3","3");
INSERT INTO stox.ratings values ("FTEO","FRONTEO Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("FUEL","Rocket Fuel Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GIGA","Giga-tronics Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GLA","Glassbridge Enterprises Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GLUU","Glu Mobile Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GOGO","Gogo Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GRVY","Gravity Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("GSUM","Gridsum Holding Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("GUID","Guidance Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("HAUP","Hauppauge Digital Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("HAWK","Blackhawk Network Holdings Inc.","2","B","9","--","--");
INSERT INTO stox.ratings values ("HDP","Hortonworks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("HIVE","Aerohive Networks","3","C","9","--","--");
INSERT INTO stox.ratings values ("HLIT","Harmonic Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("HMNY","Helios and Matheson Analytics Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("HOLI","Hollysys Automation Technologies Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("HQCL","Hanwha Q Cells Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("HUBS","HubSpot, Inc.","1","C","9","--","--");
INSERT INTO stox.ratings values ("IAIC","Information Analysis Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IDCC","InterDigital Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IDSY","ID Systems Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IGOI","iGO Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("III","Information Services Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IIN","IntriCon Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("IMI","Intermolecular Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IMMR","Immersion Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("IMPV","Imperva Inc","--","--","--","2","--");
INSERT INTO stox.ratings values ("INAP","Internap Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("INFN","Infinera Corp","--","--","--","3","--");
INSERT INTO stox.ratings values ("INOD","Innodata Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INPHQ","Interphase Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("INSE","Inspired Entertainment Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INSG","Inseego Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("INST","Instructure Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INVE","Identiv Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INVN","InvenSense Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INVT","Inventergy Global Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("INVU","Investview Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IOTS","Adesto Technologies Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("IPAS","iPass Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("IPDN","Professional Diversity Network Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("JASO","JA Solar Holdings Co Ltd","--","--","--","--","3");
INSERT INTO stox.ratings values ("JCS","Communications Systems Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("JIVE","Jive Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("JKS","JinkoSolar Holding Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("JMU","JMU Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("JTPY","JetPay Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("KEM","KEMET Corp","--","--","--","--","3");
INSERT INTO stox.ratings values ("KN","Knowles Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("KONE","Kingtone Wirelessinfo Solution Holding Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("KOPN","Kopin Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("KTCC","Key Tronic Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("KVHI","KVH Industries Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("LDKYQ","LDK Solar Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("LEJU","Leju","2","C","9","--","--");
INSERT INTO stox.ratings values ("LFGR","Leaf Group Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("LLNW","Limelight Networks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("LOCMQ","Local Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("LPSN","LivePerson Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("LQDT","Liquidity Services Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("LRAD","LRAD Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("LSCC","Lattice Semiconductor Corp","--","--","--","--","3");
INSERT INTO stox.ratings values ("LTRX","Lantronix Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("LUNA","Luna Innovations Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MARK","Remark Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MATR","Mattersight Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("MB","Mindbody Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MCHX","Marchex Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MJCO","Majesco","--","--","--","--","--");
INSERT INTO stox.ratings values ("MLNK","ModusLink Global Solutions Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MOBL","MobileIron Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MODN","Model N Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MOSY","MoSys Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MRAM","Everspin Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MRIN","Marin Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MSDI","Monster Digital Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MTLS","Materialise NV","--","--","--","--","--");
INSERT INTO stox.ratings values ("MTSI","M/A-Com","2","B","9","--","--");
INSERT INTO stox.ratings values ("MTWO","M2 Ngage Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MULE","MuleSoft Inc","2","C","9","--","--");
INSERT INTO stox.ratings values ("MVIS","MicroVision Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MX","MagnaChip Semiconductor Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("MXPT","MaxPoint Interactive Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("MXWL","Maxwell Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NAME","Rightside Group Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("NCTY","The9 Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("NEON","Neonode Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NETE","Net Element Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NEWR","New Relic Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NLST","Netlist Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NMRX","Numerex Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("NPTN","NeoPhotonics Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("NQ","NQ Mobile Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NSR","Neustar Inc","--","--","--","--","3");
INSERT INTO stox.ratings values ("NTNX","Nutanix Inc","1","C","9","--","--");
INSERT INTO stox.ratings values ("NUAN","Nuance Communications Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("NXES","Nexus Enterprise Solutions Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("OCC","Optical Cable Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("OCLR","Oclaro Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("OIIM","O2micro International Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("OKTA","Okta Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("ONSM","Onstream Media Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("ONVI","Onvia Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("P","Pandora Media, Inc.","3","C","9","--","4");
INSERT INTO stox.ratings values ("PAY","Verifone Systems Inc","--","--","--","2","--");
INSERT INTO stox.ratings values ("PCMI","PCM Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PCTI","PCTEL Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PCTY","Paylocity Corp.","1","C","9","--","--");
INSERT INTO stox.ratings values ("PFPT","Proofpoint Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PFSW","PFSweb Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PI","Impinj Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PLPM","Planet Payment Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PRCP","Perceptron Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PRGS","Progress Software Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("PRGX","PRGX Global Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PRKR","ParkerVision Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PRO","PROS Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PSDO","Presidio Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("PSTG","Pure Storage","1","C","9","--","--");
INSERT INTO stox.ratings values ("QADB","QAD Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("QBAK","Qualstar Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("QNST","Quinstreet Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("QTM","Quantum Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("QTWO","Q2 Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("QUIK","QuickLogic Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("QUMU","Qumu Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("QUOT","Quotient Technology Inc","1","C","9","--","--");
INSERT INTO stox.ratings values ("RATE","Bankrate","1","C","9","--","--");
INSERT INTO stox.ratings values ("RBCN","Rubicon Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("REDFY","Rediff.com India Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("REFR","Research Frontiers Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("RELL","Richardson Electronics Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("RESN","Resonant Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("RFIL","RF Industries Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("RMGN","RMG Networks Holding Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("RNG","RNG","1","C","9","--","--");
INSERT INTO stox.ratings values ("RNWK","RealNetworks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("RPD","Rapid7 Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("RST","Rosetta Stone Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("RSYS","Radisys Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("RUBI","Rubicon Project Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SALE","RetailMeNot Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SANM","Sanmina","--","--","--","--","3");
INSERT INTO stox.ratings values ("SCKT","Socket Mobile Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SCON","Superconductor Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SCOR","Comscore Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SCWX","SecureWorks","3","C","9","--","--");
INSERT INTO stox.ratings values ("SEAC","SeaChange International Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SFUN","Soufun Holdings Ltd-ADR","1","B","8","--","--");
INSERT INTO stox.ratings values ("SHOR","Shoretel Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SIGM","Sigma Designs Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SIMO","Silicon Motion Technology Corporation","3","C","8","--","--");
INSERT INTO stox.ratings values ("SMIT","Schmitt Industries Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SMSI","Smith Micro Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SMTX","SMTC Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("SOL","ReneSola Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("SONS","Sonus Networks Inc","--","--","--","--","3");
INSERT INTO stox.ratings values ("SPDC","Speed Commerce Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SPWR","SunPower Corp. - Class A","2","C","9","3","3");
INSERT INTO stox.ratings values ("SQNS","Sequans Communications SA","--","--","--","--","--");
INSERT INTO stox.ratings values ("SREV","ServiceSource International Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SSNI","Silver Spring Networks Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SSYS","Stratasys Ltd.","3","C","9","3","3");
INSERT INTO stox.ratings values ("STRI","STR Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SUNEQ","SunEdison Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SYNC","Synacor Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SYNT","Syntel Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("SYX","Systemax Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TAIT","Taitron Components Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TCCO","Technical Communications Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("TIGR","TigerLogic Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("TNAV","Telenav Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TNGO","Tangoe Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TRMR","Tremor Video Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TRUE","TrueCar Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TRVG","Trivago","1","C","9","--","--");
INSERT INTO stox.ratings values ("TTD","Trade Desk Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("TWLO","Twilio Inc","--","--","--","3","--");
INSERT INTO stox.ratings values ("TWOU","2U Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("UCTT","Ultra Clean Holdings Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("UIS","Unisys Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("UNXL","Uni-Pixel Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("UPLD","Upland Software Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("USAT","USA Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("VECO","Veeco Instruments","1","C","9","--","3");
INSERT INTO stox.ratings values ("VIDE","Video Display Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("VNET","21Vianet Group Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("VRNS","Varonis Systems Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("VRNT","Verint Systems Inc","--","--","--","3","--");
INSERT INTO stox.ratings values ("WK","Workiva Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("WPCS","WPCS International Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("WSTL","Westell Technologies Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("XCOMQ","Xtera Communications Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("XGTI","xG Technology Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("XNET","Xunlei Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("XTLY","Xactly Corp","--","--","--","--","--");
INSERT INTO stox.ratings values ("YELP","Yelp","2","C","9","--","--");
INSERT INTO stox.ratings values ("YEXT","Yext Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("YGE","Yingli Green Energy Holding Co Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("YRD","Yirendai Ltd","--","--","--","--","--");
INSERT INTO stox.ratings values ("YUME","YuMe Inc","--","--","--","--","--");
INSERT INTO stox.ratings values ("YY","YY","1","C","7","--","--");
INSERT INTO stox.ratings values ("ZBRA","Zebra Technologies Corp","--","--","--","3","3");
INSERT INTO stox.ratings values ("ZEN","Zendesk, Inc.","1","C","9","--","--");
INSERT INTO stox.ratings values ("ZG","Zillow","1","C","9","--","--");
INSERT INTO stox.ratings values ("ZNGA","ZYNGA","2","C","9","--","--");
